version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: broker-service-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - broker-service-network

volumes:
  postgres-data:

networks:
  broker-service-network:
    driver: bridge